### ISSUE TITLE
in lost pet report form: the background image is getting repeated when the form expands

### ISSUE THREAD

**Issue by chandel-aman** [chandel-aman/lost-and-found-pets#1]
-> open the website and on the home screen in the hero section select the "lost" action button, and you'll be directed to the lost form 
-> when you'll add the image of the pet in the lost form the form gets expanded and the background is repeated

![image](https://user-images.githubusercontent.com/97614113/216325430-51617f2e-1481-4594-8f23-c18258ba9b95.png)

**Comment by niladrix719** [comment]
can i work on this?

**Comment by taniaban2712** [comment]
can i work on this?
