### ISSUE TITLE
Updating README

### ISSUE THREAD

**Issue by the-amazing-atharva** [chandel-aman/lost-and-found-pets#11]
Hey!

I am a beginner here and I would like to contribute to the repository by making changes and adding objects to the README

**Comment by chandel-aman** [comment]
> Hey!
> 
> I am a beginner here and I would like to contribute to the repository by making changes and adding objects to the README

what objects?

**Comment by the-amazing-atharva** [comment]
github badges and icons

**Comment by the-amazing-atharva** [comment]
Any updates ??

**Comment by the-amazing-atharva** [comment]
Thanks for assigning!

Working on it soon!
