### ISSUE TITLE
the value of pet type field in the lost pet form is not getting registered

### ISSUE THREAD

**Issue by chandel-aman** [chandel-aman/lost-and-found-pets#2]
* on the home page in the hero section click the "lost" action button
* you'll be directed to the lost pet form
* in the pet type field when selecting the options the value is not getting saved, hence the form is not being submitted

![image](https://user-images.githubusercontent.com/97614113/216328165-67204f7b-cda4-42e9-a9ba-6e21289cb645.png)

**Comment by TheAkashRoy** [comment]
hey...I want to work on this issue

**Comment by rt-001** [comment]
I want to work on this issue as well.

**Comment by taniaban2712** [comment]
i want to work on this issue.
